### ISSUE TITLE
INFOGRAFIA_GESTION_DE_PROYECTOS_DE_SOFTWARE

### ISSUE THREAD

**Issue by Anna-Aparicio** [SistemasTecTlaxiaco/infografia-Anna-Aparicio-1#2]
![INFOGRAFIA_ANA_APARICIO](https://user-images.githubusercontent.com/80292858/132425558-19e2c9e4-8bb1-4655-b5dd-2ea715ebcad2.png)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Faltaron las metodologías y las herramientas...bien hecho y revisado.
